GET http://localhost:8000/courses/

@Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzaGl2YUBnbWFpbC5jb20iLCJleHAiOjE2MzQyNjE0ODIsImlhdCI6MTYzNDIyNTQ4Mn0.UMMZ34YJ3IHvuKpxE4aReR0H_VfzIpK0ww4yEwU-cE4
#@Content-type: application/json
#
#{
#    "name": "Hindi"
#}

%%%

# Duration: 63 ms
# URL: http://localhost:8000/courses/

# HTTP/1.1 200

@X-Content-Type-Options: nosniff
@X-XSS-Protection: 1; mode=block
@Cache-Control: no-cache, no-store, max-age=0, must-revalidate
@Pragma: no-cache
@Expires: 0
@X-Frame-Options: DENY
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 15 Oct 2021 11:40:57 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

[
  {
    "id": 1,
    "name": "Math"
  },
  {
    "id": 2,
    "name": "Science"
  },
  {
    "id": 3,
    "name": "Computer"
  },
  {
    "id": 4,
    "name": "Karate"
  },
  {
    "id": 5,
    "name": "Boxing"
  },
  {
    "id": 6,
    "name": "Hindi"
  }
]