POST http://localhost:8000/register

@Content-type: application/json

{
    "email": "shiva@gmail.com",
    "fullName": "Shiva Tomar",
    "password": "Shiva@1997",
    "education": "12th"
}

%%%

# Duration: 312 ms
# URL: http://localhost:8000/register

# HTTP/1.1 201

@Vary: Origin
@Vary: Access-Control-Request-Method
@Vary: Access-Control-Request-Headers
@X-Content-Type-Options: nosniff
@X-XSS-Protection: 1; mode=block
@Cache-Control: no-cache, no-store, max-age=0, must-revalidate
@Pragma: no-cache
@Expires: 0
@X-Frame-Options: DENY
@Content-Type: text/plain;charset=UTF-8
@Content-Length: 63
@Date: Fri, 15 Oct 2021 19:27:47 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

Registration successful for student with email: shiva@gmail.com